### ISSUE TITLE
Documentation: ANEMOMETER_LOSS 

### ISSUE THREAD

**Issue by Gurkengewuerz** [HarrysLapTimer/WeatherStationOne#2]
Hey Harry,

i've found your wonderful project on Prusa Printers for a self build anemometer. While it is printing i am looking at your source code.
How did you calibrated your anemometer? I saw a define for `ANEMOMETER_LOSS`. Is this a rough estimate?

https://github.com/HarrysLapTimer/WeatherStationOne/blob/main/libraries/Weather/WeatherConfig.h#L43

best regards aus dem Ruhrgebiet 🤓

**Comment by HarrysLapTimer** [comment]
That's a default value used in the code. You will override it in WeatherStationPro's Administration web front end. My current value is 1.5 - which is probably a little bit too high. It is best to do the calibration with some high quality anemometer. I had a Netatmo Anemometer available (not high quality).  Some makers install the anemometer on their car's roof and calibrate it like that. But this adds other errors: wind is not completely laminar on your roof or in the front. Due to the car's body, it will be often accelerated compared to dashboard speed.
